### ISSUE TITLE
`Incorrect translation count`—related to aliases?

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/formpack#175]
you only need a survey like this to reproduce:

type | name | label::esperanto | image
-- | -- | -- | --
note | logo |   | logo.png
text | greeting | bonan vesperon |  

the above in an [xlsform for convenience](https://github.com/kobotoolbox/formpack/files/2350438/formpack-null-translation-image_asciilabelonly.xlsx)

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/whitenoise/base.py", line 66, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python2.7/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/src/kpi/kpi/views.py", line 1106, in deployment
    serializer.save()
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/srv/src/kpi/kpi/serializers.py", line 737, in create
    active=validated_data.get('active', False))
  File "/srv/src/kpi/kpi/deployment_backends/mixin.py", line 25, in deploy
    self.connect_deployment(backend=backend, active=active)
  File "/srv/src/kpi/kpi/deployment_backends/mixin.py", line 13, in connect_deployment
    DEPLOYMENT_BACKENDS[backend](self).connect(**kwargs)
  File "/srv/src/kpi/kpi/deployment_backends/kobocat_backend.py", line 258, in connect
    'form_title': self.asset.name,
  File "/srv/src/kpi/kpi/models/asset.py", line 410, in to_xls_io
    sys.exc_info()[2]
  File "/srv/src/kpi/kpi/models/asset.py", line 399, in to_xls_io
    ss_dict = self.ordered_xlsform_content(**kwargs)
  File "/srv/src/kpi/kpi/models/asset.py", line 362, in ordered_xlsform_content
    self._xlsform_structure(content, ordered=True, kobo_specific=kobo_specific_types)
  File "/srv/src/kpi/kpi/models/asset.py", line 185, in _xlsform_structure
    **opts)
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 101, in flatten_to_spreadsheet_content
    _od[sheet_name] = _sheet_to_ordered_dicts(sheet_name, rows)
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 84, in _sheet_to_ordered_dicts
    _row_to_ordered_dict(row, OrderedDict.fromkeys(ordered_cols)) for row in rows
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/spreadsheet_content.py", line 59, in _row_to_ordered_dict
    col_order=dest.keys(),
  File "/usr/local/lib/python2.7/dist-packages/formpack/utils/flatten_content.py", line 180, in _flatten_translated_fields
    ), o_row)
Exception: asset.content improperly formatted for XLS export: ValueError(u'Incorrect translation count: "label"', {u'type': u'text', u'name': u'greeting', u'label': [u'bonan vesperon']})
```

## workaround

type | name | label::esperanto | media::image
-- | -- | -- | --
note | logo |   | logo.png
text | greeting | bonan vesperon |

**Comment by jnm** [comment]
if there are multiple `label::` translations, the `media::image` workaround above seems to display the image in Enketo only when the `default_language` (`settings` sheet) is selected. verify this and compare behavior to other translated columns
